
CREATE USER jobportal WITH PASSWORD 'jobportal';


CREATE DATABASE jobportal OWNER jobportal;


GRANT ALL PRIVILEGES ON DATABASE jobportal TO jobportal;


GRANT ALL PRIVILEGES ON ALL SCHEMAS IN DATABASE jobportal TO jobportal;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO jobportal;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO jobportal;


CREATE TABLE users_type (
  user_type_id    integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_type_name  varchar(255)
);

INSERT INTO users_type (user_type_id, user_type_name)
VALUES (1,'Recruiter'), (2,'Job Seeker');


CREATE TABLE users (
  user_id           integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email             varchar(255),
  is_active         boolean,
  password          varchar(255),
  registration_date timestamp(6),
  user_type_id      integer REFERENCES users_type(user_type_id),
  CONSTRAINT uk_users_email UNIQUE (email)
);


CREATE TABLE job_company (
  id    integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  logo  varchar(255),
  name  varchar(255)
);

CREATE TABLE job_location (
  id      integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  city    varchar(255),
  country varchar(255),
  state   varchar(255)
);


CREATE TABLE job_seeker_profile (
  user_account_id   integer PRIMARY KEY
                     REFERENCES users(user_id),
  city              varchar(255),
  country           varchar(255),
  employment_type   varchar(255),
  first_name        varchar(255),
  last_name         varchar(255),
  profile_photo     varchar(255),
  resume            varchar(255),
  state             varchar(255),
  work_authorization varchar(255)
);

CREATE TABLE recruiter_profile (
  user_account_id integer PRIMARY KEY
                   REFERENCES users(user_id),
  city            varchar(255),
  company         varchar(255),
  country         varchar(255),
  first_name      varchar(255),
  last_name       varchar(255),
  profile_photo   varchar(64),
  state           varchar(255)
);


CREATE TABLE job_post_activity (
  job_post_id        integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  description_of_job varchar(10000),
  job_title          varchar(255),
  job_type           varchar(255),
  posted_date        timestamp(6),
  remote             varchar(255),
  salary             varchar(255),
  job_company_id     integer REFERENCES job_company(id),
  job_location_id    integer REFERENCES job_location(id),
  posted_by_id       integer REFERENCES users(user_id)
);


CREATE INDEX idx_job_post_activity_company  ON job_post_activity (job_company_id);
CREATE INDEX idx_job_post_activity_location ON job_post_activity (job_location_id);
CREATE INDEX idx_job_post_activity_postedby ON job_post_activity (posted_by_id);


CREATE TABLE job_seeker_save (
  id       integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  job      integer REFERENCES job_post_activity(job_post_id),
  user_id  integer REFERENCES job_seeker_profile(user_account_id),
  CONSTRAINT uk_job_seeker_save_user_job UNIQUE (user_id, job)
);

CREATE INDEX idx_job_seeker_save_job ON job_seeker_save (job);

CREATE TABLE job_seeker_apply (
  id           integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  apply_date   timestamp(6),
  cover_letter varchar(255),
  job          integer REFERENCES job_post_activity(job_post_id),
  user_id      integer REFERENCES job_seeker_profile(user_account_id),
  CONSTRAINT uk_job_seeker_apply_user_job UNIQUE (user_id, job)
);

CREATE INDEX idx_job_seeker_apply_job ON job_seeker_apply (job);


CREATE TABLE skills (
  id                   integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  experience_level     varchar(255),
  name                 varchar(255),
  years_of_experience  varchar(255),
  job_seeker_profile   integer REFERENCES job_seeker_profile(user_account_id)
);

CREATE INDEX idx_skills_job_seeker_profile ON skills (job_seeker_profile);